'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _cfx = require('cfx.redux-types');

exports.default = (0, _cfx.toActionsTypes)({ 'INCREMENT': 'INCREMENT', 'INCREMENT_ASYNC': 'INCREMENT_ASYNC', 'DECREMENT': 'DECREMENT', 'DECREMENT_ASYNC': 'DECREMENT_ASYNC' }); // Generated by CoffeeScript 2.0.0-beta2