'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _cfx = require('cfx.redux-actions');

var _cfx2 = require('cfx.redux');

// Generated by CoffeeScript 2.0.0-beta2
var count, dd, handleActions, initialState;

handleActions = _cfx.reduxActions.handleActions;


dd = require('ddeyes');

initialState = {
  count: 0
};

count = handleActions({
  INCREMENT: function INCREMENT(state, action) {
    action.payload || (action.payload = 1);
    return state + action.payload;
  },
  DECREMENT: function DECREMENT(state, action) {
    action.payload || (action.payload = 1);
    return state - action.payload;
  }
}, 0);

exports.default = (0, _cfx2.mergeReduce)({ count: count }, initialState);