'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _cfx = require('cfx.redux-actions');

var _index = require('../constants/index');

var _index2 = _interopRequireDefault(_index);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.0.0-beta2
exports.default = (0, _cfx.createActions)(_index2.default.actions);